# Generated by Django 5.2 on 2025-04-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_borrowhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
