# Generated by Django 5.2 on 2025-05-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_book_available_copies'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_copies',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
