# Generated by Django 5.2 on 2025-05-01 06:08

import lms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_book_total_copies'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=lms.models.book_pdf_upload_path),
        ),
    ]
